apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - postgres-cluster.yaml
  - valkey.yaml
  - valkey-secret.sops.yaml
